/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Conf generated by hbm2java
 */
@Entity
@Table(name="`conf`"
)

public class Conf  implements java.io.Serializable {

    private Integer idConf;
    private String name;
    private String value_;

    public Conf() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id_conf`", nullable=false, precision=10)
    public Integer getIdConf() {
        return this.idConf;
    }
    
    public void setIdConf(Integer idConf) {
        this.idConf = idConf;
    }

    

    @Column(name="`name`", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    

    @Column(name="`value?`", nullable=false, length=25)
    public String getValue_() {
        return this.value_;
    }
    
    public void setValue_(String value_) {
        this.value_ = value_;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Conf) )
		    return false;

		 Conf that = (Conf) o;

		 return ( (this.getIdConf()==that.getIdConf()) || ( this.getIdConf()!=null && that.getIdConf()!=null && this.getIdConf().equals(that.getIdConf()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getIdConf() == null ? 0 : this.getIdConf().hashCode() );

         return result;
    }


}

