/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * EmployeeFileLocation generated by hbm2java
 */
@Entity
@Table(name="`employee_file_location`"
)

public class EmployeeFileLocation  implements java.io.Serializable {

    private Integer idEmployeeFileLocation;


@Type(type="DateTime")
    private LocalDateTime dateOfMovement;
    private Integer containerNumber;
    private String observation;
    private Integer modLocation;
    private Integer modUser;
    private Date modDate;
    private Employee employee;
    private TypeMovement typeMovement;

    public EmployeeFileLocation() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id_employee_file_location`", nullable=false, precision=10)
    public Integer getIdEmployeeFileLocation() {
        return this.idEmployeeFileLocation;
    }
    
    public void setIdEmployeeFileLocation(Integer idEmployeeFileLocation) {
        this.idEmployeeFileLocation = idEmployeeFileLocation;
    }

    

    @Column(name="`date_of_movement`", nullable=false)
    public LocalDateTime getDateOfMovement() {
        return this.dateOfMovement;
    }
    
    public void setDateOfMovement(LocalDateTime dateOfMovement) {
        this.dateOfMovement = dateOfMovement;
    }

    

    @Column(name="`container_number`", nullable=false, precision=10)
    public Integer getContainerNumber() {
        return this.containerNumber;
    }
    
    public void setContainerNumber(Integer containerNumber) {
        this.containerNumber = containerNumber;
    }

    

    @Column(name="`observation`", length=150)
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }

    

    @Column(name="`mod_location`", nullable=false, precision=10)
    public Integer getModLocation() {
        return this.modLocation;
    }
    
    public void setModLocation(Integer modLocation) {
        this.modLocation = modLocation;
    }

    

    @Column(name="`mod_user`", nullable=false, precision=10)
    public Integer getModUser() {
        return this.modUser;
    }
    
    public void setModUser(Integer modUser) {
        this.modUser = modUser;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`mod_date`", nullable=false, length=19)
    public Date getModDate() {
        return this.modDate;
    }
    
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`fk_employee`", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`fk_type_movement`", nullable=false)
    public TypeMovement getTypeMovement() {
        return this.typeMovement;
    }
    
    public void setTypeMovement(TypeMovement typeMovement) {
        this.typeMovement = typeMovement;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof EmployeeFileLocation) )
		    return false;

		 EmployeeFileLocation that = (EmployeeFileLocation) o;

		 return ( (this.getIdEmployeeFileLocation()==that.getIdEmployeeFileLocation()) || ( this.getIdEmployeeFileLocation()!=null && that.getIdEmployeeFileLocation()!=null && this.getIdEmployeeFileLocation().equals(that.getIdEmployeeFileLocation()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getIdEmployeeFileLocation() == null ? 0 : this.getIdEmployeeFileLocation().hashCode() );

         return result;
    }


}

