/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * ListRolePermission generated by hbm2java
 */
@Entity
@Table(name="`list_role_permission`"
)

public class ListRolePermission  implements java.io.Serializable {

    private Integer idListRolePermission;
    private Integer modUser;
    private Date modDate;
    private Role role;
    private RolePermission rolePermission;

    public ListRolePermission() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id_list_role_permission`", nullable=false, precision=10)
    public Integer getIdListRolePermission() {
        return this.idListRolePermission;
    }
    
    public void setIdListRolePermission(Integer idListRolePermission) {
        this.idListRolePermission = idListRolePermission;
    }

    

    @Column(name="`mod_user`", nullable=false, precision=10)
    public Integer getModUser() {
        return this.modUser;
    }
    
    public void setModUser(Integer modUser) {
        this.modUser = modUser;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`mod_date`", nullable=false, length=19)
    public Date getModDate() {
        return this.modDate;
    }
    
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`fk_role`", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`fk_role_permission`", nullable=false)
    public RolePermission getRolePermission() {
        return this.rolePermission;
    }
    
    public void setRolePermission(RolePermission rolePermission) {
        this.rolePermission = rolePermission;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof ListRolePermission) )
		    return false;

		 ListRolePermission that = (ListRolePermission) o;

		 return ( (this.getIdListRolePermission()==that.getIdListRolePermission()) || ( this.getIdListRolePermission()!=null && that.getIdListRolePermission()!=null && this.getIdListRolePermission().equals(that.getIdListRolePermission()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getIdListRolePermission() == null ? 0 : this.getIdListRolePermission().hashCode() );

         return result;
    }


}

