/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Month generated by hbm2java
 */
@Entity
@Table(name="`month`"
)

public class Month  implements java.io.Serializable {

    private Integer idMonth;
    private String nombre;
    private String name;

    public Month() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id_month`", nullable=false, precision=10)
    public Integer getIdMonth() {
        return this.idMonth;
    }
    
    public void setIdMonth(Integer idMonth) {
        this.idMonth = idMonth;
    }

    

    @Column(name="`nombre`", nullable=false, length=16)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    

    @Column(name="`name`", nullable=false, length=16)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Month) )
		    return false;

		 Month that = (Month) o;

		 return ( (this.getIdMonth()==that.getIdMonth()) || ( this.getIdMonth()!=null && that.getIdMonth()!=null && this.getIdMonth().equals(that.getIdMonth()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getIdMonth() == null ? 0 : this.getIdMonth().hashCode() );

         return result;
    }


}

