/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * OverTimeEmployee generated by hbm2java
 */
@Entity
@Table(name="`over_time_employee`"
)

public class OverTimeEmployee  implements java.io.Serializable {

    private Integer idOverTimeEmployee;


@Type(type="DateTime")
    private LocalDateTime startTime;


@Type(type="DateTime")
    private LocalDateTime endTime;
    private String observation;
    private Integer modLocation;
    private Integer modUser;
    private Date modDate;
    private Employee employee;
    private Set<ListOvertimePayroll> listOvertimePayrolls = new HashSet<ListOvertimePayroll>(0);

    public OverTimeEmployee() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id_over_time_employee`", nullable=false, precision=10)
    public Integer getIdOverTimeEmployee() {
        return this.idOverTimeEmployee;
    }
    
    public void setIdOverTimeEmployee(Integer idOverTimeEmployee) {
        this.idOverTimeEmployee = idOverTimeEmployee;
    }

    

    @Column(name="`start_time`", nullable=false)
    public LocalDateTime getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    

    @Column(name="`end_time`", nullable=false)
    public LocalDateTime getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    

    @Column(name="`observation`")
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }

    

    @Column(name="`mod_location`", nullable=false, precision=10)
    public Integer getModLocation() {
        return this.modLocation;
    }
    
    public void setModLocation(Integer modLocation) {
        this.modLocation = modLocation;
    }

    

    @Column(name="`mod_user`", nullable=false, precision=10)
    public Integer getModUser() {
        return this.modUser;
    }
    
    public void setModUser(Integer modUser) {
        this.modUser = modUser;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`mod_date`", nullable=false, length=19)
    public Date getModDate() {
        return this.modDate;
    }
    
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`fk_employee`", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="overTimeEmployee")
    public Set<ListOvertimePayroll> getListOvertimePayrolls() {
        return this.listOvertimePayrolls;
    }
    
    public void setListOvertimePayrolls(Set<ListOvertimePayroll> listOvertimePayrolls) {
        this.listOvertimePayrolls = listOvertimePayrolls;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof OverTimeEmployee) )
		    return false;

		 OverTimeEmployee that = (OverTimeEmployee) o;

		 return ( (this.getIdOverTimeEmployee()==that.getIdOverTimeEmployee()) || ( this.getIdOverTimeEmployee()!=null && that.getIdOverTimeEmployee()!=null && this.getIdOverTimeEmployee().equals(that.getIdOverTimeEmployee()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getIdOverTimeEmployee() == null ? 0 : this.getIdOverTimeEmployee().hashCode() );

         return result;
    }


}

