/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * RolePermission generated by hbm2java
 */
@Entity
@Table(name="`role_permission`"
)

public class RolePermission  implements java.io.Serializable {

    private Integer idRolePermission;
    private String rolePermissionName;
    private String spanishLabel;
    private String englishLabel;
    private String category;
    private Integer modUser;
    private Date modDate;
    private Set<ListRolePermission> listRolePermissions = new HashSet<ListRolePermission>(0);

    public RolePermission() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id_role_permission`", nullable=false, precision=10)
    public Integer getIdRolePermission() {
        return this.idRolePermission;
    }
    
    public void setIdRolePermission(Integer idRolePermission) {
        this.idRolePermission = idRolePermission;
    }

    

    @Column(name="`role_permission_name`", nullable=false, length=32)
    public String getRolePermissionName() {
        return this.rolePermissionName;
    }
    
    public void setRolePermissionName(String rolePermissionName) {
        this.rolePermissionName = rolePermissionName;
    }

    

    @Column(name="`spanish_label`", nullable=false, length=32)
    public String getSpanishLabel() {
        return this.spanishLabel;
    }
    
    public void setSpanishLabel(String spanishLabel) {
        this.spanishLabel = spanishLabel;
    }

    

    @Column(name="`english_label`", nullable=false, length=32)
    public String getEnglishLabel() {
        return this.englishLabel;
    }
    
    public void setEnglishLabel(String englishLabel) {
        this.englishLabel = englishLabel;
    }

    

    @Column(name="`category`", nullable=false, length=32)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    

    @Column(name="`mod_user`", nullable=false, precision=10)
    public Integer getModUser() {
        return this.modUser;
    }
    
    public void setModUser(Integer modUser) {
        this.modUser = modUser;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`mod_date`", nullable=false, length=19)
    public Date getModDate() {
        return this.modDate;
    }
    
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="rolePermission")
    public Set<ListRolePermission> getListRolePermissions() {
        return this.listRolePermissions;
    }
    
    public void setListRolePermissions(Set<ListRolePermission> listRolePermissions) {
        this.listRolePermissions = listRolePermissions;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof RolePermission) )
		    return false;

		 RolePermission that = (RolePermission) o;

		 return ( (this.getIdRolePermission()==that.getIdRolePermission()) || ( this.getIdRolePermission()!=null && that.getIdRolePermission()!=null && this.getIdRolePermission().equals(that.getIdRolePermission()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getIdRolePermission() == null ? 0 : this.getIdRolePermission().hashCode() );

         return result;
    }


}

