/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * ScheduleFixedDay generated by hbm2java
 */
@Entity
@Table(name="`schedule_fixed_day`"
)

public class ScheduleFixedDay  implements java.io.Serializable {

    private Integer idScheduleFixedDay;
    private Boolean weekDay;
    private Date checkIn;
    private Date lunchStartTime;
    private Date lunchHourOrder;
    private Date outputTime;
    private Integer modUser;
    private Date modDate;
    private ScheduleFixed scheduleFixed;

    public ScheduleFixedDay() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id_schedule_fixed_day`", nullable=false, precision=10)
    public Integer getIdScheduleFixedDay() {
        return this.idScheduleFixedDay;
    }
    
    public void setIdScheduleFixedDay(Integer idScheduleFixedDay) {
        this.idScheduleFixedDay = idScheduleFixedDay;
    }

    

    @Column(name="`week_day`", nullable=false)
    public Boolean getWeekDay() {
        return this.weekDay;
    }
    
    public void setWeekDay(Boolean weekDay) {
        this.weekDay = weekDay;
    }

    @Temporal(TemporalType.TIME)

    @Column(name="`check_in`", nullable=false, length=8)
    public Date getCheckIn() {
        return this.checkIn;
    }
    
    public void setCheckIn(Date checkIn) {
        this.checkIn = checkIn;
    }

    @Temporal(TemporalType.TIME)

    @Column(name="`lunch_start_time`", nullable=false, length=8)
    public Date getLunchStartTime() {
        return this.lunchStartTime;
    }
    
    public void setLunchStartTime(Date lunchStartTime) {
        this.lunchStartTime = lunchStartTime;
    }

    @Temporal(TemporalType.TIME)

    @Column(name="`lunch_hour_order`", nullable=false, length=8)
    public Date getLunchHourOrder() {
        return this.lunchHourOrder;
    }
    
    public void setLunchHourOrder(Date lunchHourOrder) {
        this.lunchHourOrder = lunchHourOrder;
    }

    @Temporal(TemporalType.TIME)

    @Column(name="`output_time`", nullable=false, length=8)
    public Date getOutputTime() {
        return this.outputTime;
    }
    
    public void setOutputTime(Date outputTime) {
        this.outputTime = outputTime;
    }

    

    @Column(name="`mod_user`", nullable=false, precision=10)
    public Integer getModUser() {
        return this.modUser;
    }
    
    public void setModUser(Integer modUser) {
        this.modUser = modUser;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`mod_date`", nullable=false, length=19)
    public Date getModDate() {
        return this.modDate;
    }
    
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`fk_schedule_fixed`", nullable=false)
    public ScheduleFixed getScheduleFixed() {
        return this.scheduleFixed;
    }
    
    public void setScheduleFixed(ScheduleFixed scheduleFixed) {
        this.scheduleFixed = scheduleFixed;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof ScheduleFixedDay) )
		    return false;

		 ScheduleFixedDay that = (ScheduleFixedDay) o;

		 return ( (this.getIdScheduleFixedDay()==that.getIdScheduleFixedDay()) || ( this.getIdScheduleFixedDay()!=null && that.getIdScheduleFixedDay()!=null && this.getIdScheduleFixedDay().equals(that.getIdScheduleFixedDay()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getIdScheduleFixedDay() == null ? 0 : this.getIdScheduleFixedDay().hashCode() );

         return result;
    }


}

