/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * WorkPositionPerformanceIndicator generated by hbm2java
 */
@Entity
@Table(name="`work_position_performance_indicator`"
)

public class WorkPositionPerformanceIndicator  implements java.io.Serializable {

    private Integer idWorkPositionPerformanceIndicator;
    private String indicator;
    private String observation;
    private Integer modUser;
    private Date modDate;
    private WorkPosition workPosition;
    private Set<AssessmentField> assessmentFields = new HashSet<AssessmentField>(0);

    public WorkPositionPerformanceIndicator() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id_work_position_performance_indicator`", nullable=false, precision=10)
    public Integer getIdWorkPositionPerformanceIndicator() {
        return this.idWorkPositionPerformanceIndicator;
    }
    
    public void setIdWorkPositionPerformanceIndicator(Integer idWorkPositionPerformanceIndicator) {
        this.idWorkPositionPerformanceIndicator = idWorkPositionPerformanceIndicator;
    }

    

    @Column(name="`indicator`", nullable=false, length=100)
    public String getIndicator() {
        return this.indicator;
    }
    
    public void setIndicator(String indicator) {
        this.indicator = indicator;
    }

    

    @Column(name="`observation`", nullable=false)
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }

    

    @Column(name="`mod_user`", nullable=false, precision=10)
    public Integer getModUser() {
        return this.modUser;
    }
    
    public void setModUser(Integer modUser) {
        this.modUser = modUser;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`mod_date`", nullable=false, length=19)
    public Date getModDate() {
        return this.modDate;
    }
    
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`fk_work_position`", nullable=false)
    public WorkPosition getWorkPosition() {
        return this.workPosition;
    }
    
    public void setWorkPosition(WorkPosition workPosition) {
        this.workPosition = workPosition;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="workPositionPerformanceIndicator")
    public Set<AssessmentField> getAssessmentFields() {
        return this.assessmentFields;
    }
    
    public void setAssessmentFields(Set<AssessmentField> assessmentFields) {
        this.assessmentFields = assessmentFields;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof WorkPositionPerformanceIndicator) )
		    return false;

		 WorkPositionPerformanceIndicator that = (WorkPositionPerformanceIndicator) o;

		 return ( (this.getIdWorkPositionPerformanceIndicator()==that.getIdWorkPositionPerformanceIndicator()) || ( this.getIdWorkPositionPerformanceIndicator()!=null && that.getIdWorkPositionPerformanceIndicator()!=null && this.getIdWorkPositionPerformanceIndicator().equals(that.getIdWorkPositionPerformanceIndicator()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getIdWorkPositionPerformanceIndicator() == null ? 0 : this.getIdWorkPositionPerformanceIndicator().hashCode() );

         return result;
    }


}

