/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.test_25feb.dynamohr126tabs.*;

/**
 * Service object for domain model class ListPeriodicBonusPayroll.
 * @see com.test_25feb.dynamohr126tabs.ListPeriodicBonusPayroll
 */

public interface ListPeriodicBonusPayrollService {
   /**
	 * Creates a new listperiodicbonuspayroll.
	 * 
	 * @param created
	 *            The information of the created listperiodicbonuspayroll.
	 * @return The created listperiodicbonuspayroll.
	 */
	public ListPeriodicBonusPayroll create(ListPeriodicBonusPayroll created);

	/**
	 * Deletes a listperiodicbonuspayroll.
	 * 
	 * @param listperiodicbonuspayrollId
	 *            The id of the deleted listperiodicbonuspayroll.
	 * @return The deleted listperiodicbonuspayroll.
	 * @throws EntityNotFoundException
	 *             if no listperiodicbonuspayroll is found with the given id.
	 */
	public ListPeriodicBonusPayroll delete(Integer listperiodicbonuspayrollId) throws EntityNotFoundException;

	/**
	 * Finds all listperiodicbonuspayrolls.
	 * 
	 * @return A list of listperiodicbonuspayrolls.
	 */
	public Page<ListPeriodicBonusPayroll> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<ListPeriodicBonusPayroll> findAll(Pageable pageable);
	
	/**
	 * Finds listperiodicbonuspayroll by id.
	 * 
	 * @param id
	 *            The id of the wanted listperiodicbonuspayroll.
	 * @return The found listperiodicbonuspayroll. If no listperiodicbonuspayroll is found, this method returns
	 *         null.
	 */
	public ListPeriodicBonusPayroll findById(Integer id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a listperiodicbonuspayroll.
	 * 
	 * @param updated
	 *            The information of the updated listperiodicbonuspayroll.
	 * @return The updated listperiodicbonuspayroll.
	 * @throws EntityNotFoundException
	 *             if no listperiodicbonuspayroll is found with given id.
	 */
	public ListPeriodicBonusPayroll update(ListPeriodicBonusPayroll updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the listperiodicbonuspayrolls in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the listperiodicbonuspayroll.
	 */

	public long countAll();


    public Page<ListPeriodicBonusPayroll> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

