/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_25feb.dynamohr126tabs.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.test_25feb.dynamohr126tabs.*;

/**
 * Service object for domain model class TypeAbsenceJustification.
 * @see com.test_25feb.dynamohr126tabs.TypeAbsenceJustification
 */

public interface TypeAbsenceJustificationService {
   /**
	 * Creates a new typeabsencejustification.
	 * 
	 * @param created
	 *            The information of the created typeabsencejustification.
	 * @return The created typeabsencejustification.
	 */
	public TypeAbsenceJustification create(TypeAbsenceJustification created);

	/**
	 * Deletes a typeabsencejustification.
	 * 
	 * @param typeabsencejustificationId
	 *            The id of the deleted typeabsencejustification.
	 * @return The deleted typeabsencejustification.
	 * @throws EntityNotFoundException
	 *             if no typeabsencejustification is found with the given id.
	 */
	public TypeAbsenceJustification delete(Integer typeabsencejustificationId) throws EntityNotFoundException;

	/**
	 * Finds all typeabsencejustifications.
	 * 
	 * @return A list of typeabsencejustifications.
	 */
	public Page<TypeAbsenceJustification> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<TypeAbsenceJustification> findAll(Pageable pageable);
	
	/**
	 * Finds typeabsencejustification by id.
	 * 
	 * @param id
	 *            The id of the wanted typeabsencejustification.
	 * @return The found typeabsencejustification. If no typeabsencejustification is found, this method returns
	 *         null.
	 */
	public TypeAbsenceJustification findById(Integer id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a typeabsencejustification.
	 * 
	 * @param updated
	 *            The information of the updated typeabsencejustification.
	 * @return The updated typeabsencejustification.
	 * @throws EntityNotFoundException
	 *             if no typeabsencejustification is found with given id.
	 */
	public TypeAbsenceJustification update(TypeAbsenceJustification updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the typeabsencejustifications in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the typeabsencejustification.
	 */

	public long countAll();


    public Page<TypeAbsenceJustification> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

